language: node_js

node_js:
  - lts/*

stages:
  - Test
  - name: Release
    if: branch = master AND commit_message !~ /(release|no-release)/

install:
  - npm config set package-lock false
  - npm install

jobs:
  include:
    - stage: Test
      script: npm run test
      after_success:
        - curl "https://api.microlink.io?url=https://cards.microlink.io&meta=false&insights&embed=insights.lighthouse&force" > ".lighthouseci/lhr-$(date +"%s").json
        - lhci upload --upload.token="$LHCI_SERVER_TOKEN"
    - stage: Release
      before_deploy:
        - git config user.email ${GITHUB_EMAIL:-"travis@travis-ci.org"}
        - git config user.name ${GITHUB_USER:-"Travis CI"}
        - git remote set-url origin https://${GH_TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git
        - git checkout master
      deploy:
        skip_cleanup: true
        provider: script
        script: npm run release
        on:
          branch: master
